from enum import Enum


class ConflictType(str, Enum):
    TEACHER_DOUBLE_BOOKING = "TEACHER_DOUBLE_BOOKING"
    ROOM_DOUBLE_BOOKING = "ROOM_DOUBLE_BOOKING"
    CLASS_DOUBLE_BOOKING = "CLASS_DOUBLE_BOOKING"
    TEACHER_LEAVE_CONFLICT = "TEACHER_LEAVE_CONFLICT"
    HOLIDAY_CONFLICT = "HOLIDAY_CONFLICT"
    MAX_WORKLOAD = "MAX_WORKLOAD"
    ROOM_CAPACITY = "ROOM_CAPACITY"
    TEACHER_AVAILABILITY = "TEACHER_AVAILABILITY"


class ConflictSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    WARNING = "WARNING"


class ConflictStatus(str, Enum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"
