from enum import Enum


class DocumentType(str, Enum):
    """Enumeration of supported student document types."""

    PHOTO = "PHOTO"
    AADHAAR = "AADHAAR"
    BIRTH_CERTIFICATE = "BIRTH_CERTIFICATE"
    TRANSFER_CERTIFICATE = "TRANSFER_CERTIFICATE"
    COMMUNITY_CERTIFICATE = "COMMUNITY_CERTIFICATE"
    MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE"
    PASSPORT = "PASSPORT"
    MARKSHEET = "MARKSHEET"
    ADDRESS_PROOF = "ADDRESS_PROOF"
    INCOME_CERTIFICATE = "INCOME_CERTIFICATE"
    OTHER = "OTHER"
