from enum import StrEnum


class DocumentType(StrEnum):
    IDENTITY_PROOF = "IDENTITY_PROOF"
    ADDRESS_PROOF = "ADDRESS_PROOF"
    ACADEMIC_CERTIFICATE = "ACADEMIC_CERTIFICATE"
    PROFESSIONAL_DOCUMENT = "PROFESSIONAL_DOCUMENT"
    FINANCIAL_DOCUMENT = "FINANCIAL_DOCUMENT"
    COMPLIANCE = "COMPLIANCE"
    OTHER = "OTHER"


class DocumentCategory(StrEnum):
    PERSONAL = "PERSONAL"
    ACADEMIC = "ACADEMIC"
    PROFESSIONAL = "PROFESSIONAL"
    FINANCIAL = "FINANCIAL"
    LEGAL = "LEGAL"
    OTHER = "OTHER"


class VerificationStatus(StrEnum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class DocumentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
