from enum import Enum


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RuleType(str, Enum):
    TEACHER_AVAILABILITY = "TEACHER_AVAILABILITY"
    TEACHER_WORKLOAD = "TEACHER_WORKLOAD"
    SUBJECT_LIMIT = "SUBJECT_LIMIT"
    ROOM_CAPACITY = "ROOM_CAPACITY"
    PREFERRED_ROOM = "PREFERRED_ROOM"
    PREFERRED_TEACHER = "PREFERRED_TEACHER"


class ResultStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
