"""create student table

Revision ID: 08122a0db6fa
Revises: 501bb12aacf8
Create Date: 2026-07-25 16:07:57.556882

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08122a0db6fa'
down_revision: str | Sequence[str] | None = '501bb12aacf8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('emis_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('caste', sa.String(length=50), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('mother_tongue', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'TRANSFERRED', 'GRADUATED', 'DROPPED', 'ALUMNI', name='studentstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'admission_number', name='uq_students_school_admission')
    )
    op.create_index(op.f('ix_students_admission_number'), 'students', ['admission_number'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_admission_number'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
