"""create_teachers_table

Revision ID: 0c1687060520
Revises: f49bf9343b8e
Create Date: 2026-07-29 13:30:09.641149

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c1687060520"
down_revision: str | Sequence[str] | None = "f49bf9343b8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teachers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("teacher_code", sa.String(length=50), nullable=False),
        sa.Column(
            "teacher_type",
            sa.Enum(
                "PRIMARY",
                "SECONDARY",
                "HIGHER_SECONDARY",
                "SPECIAL_EDUCATION",
                name="teachertype",
            ),
            nullable=False,
        ),
        sa.Column(
            "employment_mode",
            sa.Enum(
                "FULL_TIME", "PART_TIME", "CONTRACT", "GUEST", name="employmentmode"
            ),
            nullable=False,
        ),
        sa.Column("joining_academic_year_id", sa.UUID(), nullable=True),
        sa.Column("primary_department_id", sa.UUID(), nullable=False),
        sa.Column("staff_room", sa.String(length=100), nullable=True),
        sa.Column("official_email", sa.String(length=255), nullable=True),
        sa.Column("extension_number", sa.String(length=20), nullable=True),
        sa.Column("office_location", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("teaching_experience_years", sa.Integer(), nullable=False),
        sa.Column("highest_qualification", sa.String(length=150), nullable=True),
        sa.Column("specialization", sa.String(length=150), nullable=True),
        sa.Column("subject_preferences", sa.JSON(), nullable=True),
        sa.Column("class_teacher_preference", sa.String(length=100), nullable=True),
        sa.Column("max_teaching_hours_per_week", sa.Integer(), nullable=False),
        sa.Column("is_class_teacher", sa.Boolean(), nullable=False),
        sa.Column("is_subject_teacher", sa.Boolean(), nullable=False),
        sa.Column("is_exam_evaluator", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["joining_academic_year_id"], ["academic_years.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["primary_department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "official_email", name="uq_teachers_school_email"
        ),
        sa.UniqueConstraint(
            "school_id", "teacher_code", name="uq_teachers_school_code"
        ),
    )
    op.create_index(
        op.f("ix_teachers_employee_id"), "teachers", ["employee_id"], unique=True
    )
    op.create_index(op.f("ix_teachers_id"), "teachers", ["id"], unique=False)
    op.create_index(
        op.f("ix_teachers_school_id"), "teachers", ["school_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teachers_school_id"), table_name="teachers")
    op.drop_index(op.f("ix_teachers_id"), table_name="teachers")
    op.drop_index(op.f("ix_teachers_employee_id"), table_name="teachers")
    op.drop_table("teachers")
    # ### end Alembic commands ###
