"""create student academic assignment tables

Revision ID: 0e52de15a299
Revises: d326d7669a9f
Create Date: 2026-07-26 04:03:04.432339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e52de15a299"
down_revision: str | Sequence[str] | None = "d326d7669a9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_academic_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("roll_number", sa.String(length=20), nullable=True),
        sa.Column("admission_type", sa.String(length=50), nullable=True),
        sa.Column("joined_on", sa.Date(), nullable=False),
        sa.Column("left_on", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "TRANSFERRED",
                "PROMOTED",
                "GRADUATED",
                "LEFT",
                name="assignmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id",
            "academic_year_id",
            "class_id",
            "section_id",
            "roll_number",
            name="uq_assignments_roll_number",
        ),
    )
    op.create_index(
        op.f("ix_student_academic_assignments_academic_year_id"),
        "student_academic_assignments",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_academic_assignments_class_id"),
        "student_academic_assignments",
        ["class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_academic_assignments_id"),
        "student_academic_assignments",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_academic_assignments_school_id"),
        "student_academic_assignments",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_academic_assignments_section_id"),
        "student_academic_assignments",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_academic_assignments_student_id"),
        "student_academic_assignments",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_student_academic_assignments_student_id"),
        table_name="student_academic_assignments",
    )
    op.drop_index(
        op.f("ix_student_academic_assignments_section_id"),
        table_name="student_academic_assignments",
    )
    op.drop_index(
        op.f("ix_student_academic_assignments_school_id"),
        table_name="student_academic_assignments",
    )
    op.drop_index(
        op.f("ix_student_academic_assignments_id"),
        table_name="student_academic_assignments",
    )
    op.drop_index(
        op.f("ix_student_academic_assignments_class_id"),
        table_name="student_academic_assignments",
    )
    op.drop_index(
        op.f("ix_student_academic_assignments_academic_year_id"),
        table_name="student_academic_assignments",
    )
    op.drop_table("student_academic_assignments")
    # ### end Alembic commands ###
