"""create_subject_groups_and_mappings_tables

Revision ID: 248db750e199
Revises: 893be610e5bf
Create Date: 2026-07-26 09:23:08.257621

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "248db750e199"
down_revision: str | Sequence[str] | None = "893be610e5bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("group_code", sa.String(length=50), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("minimum_subjects", sa.Integer(), nullable=False),
        sa.Column("maximum_subjects", sa.Integer(), nullable=False),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column("is_elective", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="subjectgroupstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "group_code", name="uq_subject_groups_school_code"
        ),
        sa.UniqueConstraint(
            "school_id", "group_name", name="uq_subject_groups_school_name"
        ),
    )
    op.create_index(
        op.f("ix_subject_groups_id"), "subject_groups", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_subject_groups_school_id"),
        "subject_groups",
        ["school_id"],
        unique=False,
    )
    op.create_table(
        "subject_group_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("subject_group_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subject_group_id"], ["subject_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_group_id", "subject_id", name="uq_sg_mappings_group_subject"
        ),
    )
    op.create_index(
        op.f("ix_subject_group_mappings_id"),
        "subject_group_mappings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_group_mappings_school_id"),
        "subject_group_mappings",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_group_mappings_subject_group_id"),
        "subject_group_mappings",
        ["subject_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_group_mappings_subject_id"),
        "subject_group_mappings",
        ["subject_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subject_group_mappings_subject_id"),
        table_name="subject_group_mappings",
    )
    op.drop_index(
        op.f("ix_subject_group_mappings_subject_group_id"),
        table_name="subject_group_mappings",
    )
    op.drop_index(
        op.f("ix_subject_group_mappings_school_id"), table_name="subject_group_mappings"
    )
    op.drop_index(
        op.f("ix_subject_group_mappings_id"), table_name="subject_group_mappings"
    )
    op.drop_table("subject_group_mappings")
    op.drop_index(op.f("ix_subject_groups_school_id"), table_name="subject_groups")
    op.drop_index(op.f("ix_subject_groups_id"), table_name="subject_groups")
    op.drop_table("subject_groups")
    op.execute("DROP TYPE IF EXISTS subjectgroupstatus")
    # ### end Alembic commands ###
