"""create_timetable_adjustment_substitution_tables

Revision ID: 31721f4b5564
Revises: ec7518460191
Create Date: 2026-08-01 13:33:46.132668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31721f4b5564'
down_revision: Union[str, Sequence[str], None] = 'ec7518460191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_substitutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('original_teacher_id', sa.UUID(), nullable=False),
    sa.Column('substitute_teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('substitution_type', sa.Enum('PLANNED', 'EMERGENCY', 'PERMANENT', name='teacher_substitution_type'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='teacher_substitution_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_substitution_school_status', 'teacher_substitutions', ['school_id', 'status'], unique=False)
    op.create_index('ix_teacher_substitution_slot', 'teacher_substitutions', ['substitute_teacher_id', 'working_day_id', 'time_slot_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_class_id'), 'teacher_substitutions', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_id'), 'teacher_substitutions', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_original_teacher_id'), 'teacher_substitutions', ['original_teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_school_id'), 'teacher_substitutions', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_section_id'), 'teacher_substitutions', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_status'), 'teacher_substitutions', ['status'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_subject_id'), 'teacher_substitutions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_substitute_teacher_id'), 'teacher_substitutions', ['substitute_teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_time_slot_id'), 'teacher_substitutions', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_teacher_substitutions_working_day_id'), 'teacher_substitutions', ['working_day_id'], unique=False)
    op.create_table('substitution_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('substitution_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitution_id'], ['teacher_substitutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitution_histories_id'), 'substitution_histories', ['id'], unique=False)
    op.create_index(op.f('ix_substitution_histories_school_id'), 'substitution_histories', ['school_id'], unique=False)
    op.create_index(op.f('ix_substitution_histories_substitution_id'), 'substitution_histories', ['substitution_id'], unique=False)
    op.create_table('timetable_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_timetable_entry_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('TEACHER_CHANGE', 'ROOM_CHANGE', 'TIME_SLOT_CHANGE', 'WORKING_DAY_CHANGE', 'SUBJECT_CHANGE', 'EMERGENCY_ADJUSTMENT', name='timetable_adjustment_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('old_teacher_id', sa.UUID(), nullable=True),
    sa.Column('old_room_id', sa.UUID(), nullable=True),
    sa.Column('old_time_slot_id', sa.UUID(), nullable=True),
    sa.Column('old_working_day_id', sa.UUID(), nullable=True),
    sa.Column('new_teacher_id', sa.UUID(), nullable=True),
    sa.Column('new_room_id', sa.UUID(), nullable=True),
    sa.Column('new_time_slot_id', sa.UUID(), nullable=True),
    sa.Column('new_working_day_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', 'ROLLED_BACK', 'EXPIRED', name='timetable_adjustment_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_timetable_entry_id'], ['class_timetable_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_time_slot_id'], ['time_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_working_day_id'], ['working_days.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_time_slot_id'], ['time_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_working_day_id'], ['working_days.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timetable_adjustment_entry', 'timetable_adjustments', ['class_timetable_entry_id', 'status'], unique=False)
    op.create_index('ix_timetable_adjustment_school_status', 'timetable_adjustments', ['school_id', 'status'], unique=False)
    op.create_index(op.f('ix_timetable_adjustments_class_timetable_entry_id'), 'timetable_adjustments', ['class_timetable_entry_id'], unique=False)
    op.create_index(op.f('ix_timetable_adjustments_id'), 'timetable_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_adjustments_school_id'), 'timetable_adjustments', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_adjustments_status'), 'timetable_adjustments', ['status'], unique=False)
    op.create_table('adjustment_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['adjustment_id'], ['timetable_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustment_histories_adjustment_id'), 'adjustment_histories', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_adjustment_histories_id'), 'adjustment_histories', ['id'], unique=False)
    op.create_index(op.f('ix_adjustment_histories_school_id'), 'adjustment_histories', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustment_histories_school_id'), table_name='adjustment_histories')
    op.drop_index(op.f('ix_adjustment_histories_id'), table_name='adjustment_histories')
    op.drop_index(op.f('ix_adjustment_histories_adjustment_id'), table_name='adjustment_histories')
    op.drop_table('adjustment_histories')
    op.drop_index(op.f('ix_timetable_adjustments_status'), table_name='timetable_adjustments')
    op.drop_index(op.f('ix_timetable_adjustments_school_id'), table_name='timetable_adjustments')
    op.drop_index(op.f('ix_timetable_adjustments_id'), table_name='timetable_adjustments')
    op.drop_index(op.f('ix_timetable_adjustments_class_timetable_entry_id'), table_name='timetable_adjustments')
    op.drop_index('ix_timetable_adjustment_school_status', table_name='timetable_adjustments')
    op.drop_index('ix_timetable_adjustment_entry', table_name='timetable_adjustments')
    op.drop_table('timetable_adjustments')
    op.drop_index(op.f('ix_substitution_histories_substitution_id'), table_name='substitution_histories')
    op.drop_index(op.f('ix_substitution_histories_school_id'), table_name='substitution_histories')
    op.drop_index(op.f('ix_substitution_histories_id'), table_name='substitution_histories')
    op.drop_table('substitution_histories')
    op.drop_index(op.f('ix_teacher_substitutions_working_day_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_time_slot_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_substitute_teacher_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_subject_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_status'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_section_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_school_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_original_teacher_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_id'), table_name='teacher_substitutions')
    op.drop_index(op.f('ix_teacher_substitutions_class_id'), table_name='teacher_substitutions')
    op.drop_index('ix_teacher_substitution_slot', table_name='teacher_substitutions')
    op.drop_index('ix_teacher_substitution_school_status', table_name='teacher_substitutions')
    op.drop_table('teacher_substitutions')
    # ### end Alembic commands ###
