"""create_academic_settings_table

Revision ID: 36700004d515
Revises: 6ac6020e1afb
Create Date: 2026-07-26 09:52:25.153588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36700004d515"
down_revision: str | Sequence[str] | None = "6ac6020e1afb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("default_term_id", sa.UUID(), nullable=True),
        sa.Column("default_language", sa.String(length=50), nullable=False),
        sa.Column("grading_system", sa.String(length=50), nullable=False),
        sa.Column(
            "attendance_calculation_method", sa.String(length=50), nullable=False
        ),
        sa.Column("promotion_policy", sa.Text(), nullable=True),
        sa.Column(
            "passing_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "minimum_attendance_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column("maximum_subjects_per_day", sa.Integer(), nullable=False),
        sa.Column("maximum_periods_per_day", sa.Integer(), nullable=False),
        sa.Column("working_days_per_week", sa.Integer(), nullable=False),
        sa.Column("academic_timezone", sa.String(length=50), nullable=False),
        sa.Column("academic_calendar_type", sa.String(length=50), nullable=False),
        sa.Column("week_start_day", sa.String(length=20), nullable=False),
        sa.Column("allow_subject_electives", sa.Boolean(), nullable=False),
        sa.Column("allow_cross_section_subjects", sa.Boolean(), nullable=False),
        sa.Column("allow_student_transfers", sa.Boolean(), nullable=False),
        sa.Column("allow_mid_year_admission", sa.Boolean(), nullable=False),
        sa.Column("auto_generate_roll_numbers", sa.Boolean(), nullable=False),
        sa.Column("roll_number_prefix", sa.String(length=20), nullable=True),
        sa.Column("roll_number_padding", sa.Integer(), nullable=False),
        sa.Column("default_class_capacity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="academicsettingsstatus"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"], ["academic_years.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["default_term_id"], ["terms.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "academic_year_id", name="uq_academic_settings_school_year"
        ),
    )
    op.create_index(
        op.f("ix_academic_settings_academic_year_id"),
        "academic_settings",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_academic_settings_default_term_id"),
        "academic_settings",
        ["default_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_academic_settings_id"), "academic_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_academic_settings_school_id"),
        "academic_settings",
        ["school_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_academic_settings_school_id"), table_name="academic_settings"
    )
    op.drop_index(op.f("ix_academic_settings_id"), table_name="academic_settings")
    op.drop_index(
        op.f("ix_academic_settings_default_term_id"), table_name="academic_settings"
    )
    op.drop_index(
        op.f("ix_academic_settings_academic_year_id"), table_name="academic_settings"
    )
    op.drop_table("academic_settings")
    # ### end Alembic commands ###
