"""create_teacher_subject_allocation_tables

Revision ID: 4654f14ee87b
Revises: 880d485af3f2
Create Date: 2026-07-31 19:23:55.470001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4654f14ee87b'
down_revision: Union[str, Sequence[str], None] = '880d485af3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('qualification_level', sa.String(length=100), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_qualifications_id'), 'subject_qualifications', ['id'], unique=False)
    op.create_index(op.f('ix_subject_qualifications_school_id'), 'subject_qualifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_subject_qualifications_subject_id'), 'subject_qualifications', ['subject_id'], unique=False)
    op.create_index(op.f('ix_subject_qualifications_teacher_id'), 'subject_qualifications', ['teacher_id'], unique=False)
    op.create_index('ix_uq_school_subject_qualification', 'subject_qualifications', ['school_id', 'teacher_id', 'subject_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('teacher_subject_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weekly_period_limit', sa.Integer(), nullable=False),
    sa.Column('assigned_periods', sa.Integer(), nullable=False),
    sa.Column('preferred_room_id', sa.UUID(), nullable=True),
    sa.Column('preferred_shift_id', sa.UUID(), nullable=True),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=False),
    sa.Column('is_primary_teacher', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='allocation_status'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_shift_id'], ['attendance_shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_subject_allocations_academic_year_id'), 'teacher_subject_allocations', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_class_id'), 'teacher_subject_allocations', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_id'), 'teacher_subject_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_school_id'), 'teacher_subject_allocations', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_section_id'), 'teacher_subject_allocations', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_subject_id'), 'teacher_subject_allocations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_teacher_id'), 'teacher_subject_allocations', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_allocations_term_id'), 'teacher_subject_allocations', ['term_id'], unique=False)
    op.create_index('ix_uq_school_teacher_allocation', 'teacher_subject_allocations', ['school_id', 'teacher_id', 'academic_year_id', 'term_id', 'class_id', 'section_id', 'subject_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('teacher_workloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('maximum_weekly_periods', sa.Integer(), nullable=False),
    sa.Column('allocated_periods', sa.Integer(), nullable=False),
    sa.Column('remaining_periods', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('consecutive_period_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_workloads_id'), 'teacher_workloads', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_workloads_school_id'), 'teacher_workloads', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_workloads_teacher_id'), 'teacher_workloads', ['teacher_id'], unique=False)
    op.create_index('ix_uq_school_teacher_workload', 'teacher_workloads', ['school_id', 'teacher_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_school_teacher_workload', table_name='teacher_workloads', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_teacher_workloads_teacher_id'), table_name='teacher_workloads')
    op.drop_index(op.f('ix_teacher_workloads_school_id'), table_name='teacher_workloads')
    op.drop_index(op.f('ix_teacher_workloads_id'), table_name='teacher_workloads')
    op.drop_table('teacher_workloads')
    op.drop_index('ix_uq_school_teacher_allocation', table_name='teacher_subject_allocations', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_teacher_subject_allocations_term_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_teacher_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_subject_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_section_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_school_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_class_id'), table_name='teacher_subject_allocations')
    op.drop_index(op.f('ix_teacher_subject_allocations_academic_year_id'), table_name='teacher_subject_allocations')
    op.drop_table('teacher_subject_allocations')
    op.drop_index('ix_uq_school_subject_qualification', table_name='subject_qualifications', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_subject_qualifications_teacher_id'), table_name='subject_qualifications')
    op.drop_index(op.f('ix_subject_qualifications_subject_id'), table_name='subject_qualifications')
    op.drop_index(op.f('ix_subject_qualifications_school_id'), table_name='subject_qualifications')
    op.drop_index(op.f('ix_subject_qualifications_id'), table_name='subject_qualifications')
    op.drop_table('subject_qualifications')
    # ### end Alembic commands ###
