"""create student progression tables

Revision ID: 488d989b26e0
Revises: 0e52de15a299
Create Date: 2026-07-26 04:11:39.314049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "488d989b26e0"
down_revision: str | Sequence[str] | None = "0e52de15a299"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_progressions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("from_academic_year_id", sa.Uuid(), nullable=True),
        sa.Column("to_academic_year_id", sa.Uuid(), nullable=True),
        sa.Column("from_class_id", sa.Uuid(), nullable=True),
        sa.Column("to_class_id", sa.Uuid(), nullable=True),
        sa.Column("from_section_id", sa.Uuid(), nullable=True),
        sa.Column("to_section_id", sa.Uuid(), nullable=True),
        sa.Column("old_roll_number", sa.String(length=20), nullable=True),
        sa.Column("new_roll_number", sa.String(length=20), nullable=True),
        sa.Column(
            "progression_type",
            sa.Enum(
                "PROMOTION",
                "TRANSFER",
                "GRADUATION",
                "ALUMNI",
                "REPEAT_CLASS",
                "WITHDRAWAL",
                name="progressiontype",
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_progressions_from_academic_year_id"),
        "student_progressions",
        ["from_academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_from_class_id"),
        "student_progressions",
        ["from_class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_from_section_id"),
        "student_progressions",
        ["from_section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_id"), "student_progressions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_student_progressions_progression_type"),
        "student_progressions",
        ["progression_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_school_id"),
        "student_progressions",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_student_id"),
        "student_progressions",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_to_academic_year_id"),
        "student_progressions",
        ["to_academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_to_class_id"),
        "student_progressions",
        ["to_class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_progressions_to_section_id"),
        "student_progressions",
        ["to_section_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_student_progressions_to_section_id"), table_name="student_progressions"
    )
    op.drop_index(
        op.f("ix_student_progressions_to_class_id"), table_name="student_progressions"
    )
    op.drop_index(
        op.f("ix_student_progressions_to_academic_year_id"),
        table_name="student_progressions",
    )
    op.drop_index(
        op.f("ix_student_progressions_student_id"), table_name="student_progressions"
    )
    op.drop_index(
        op.f("ix_student_progressions_school_id"), table_name="student_progressions"
    )
    op.drop_index(
        op.f("ix_student_progressions_progression_type"),
        table_name="student_progressions",
    )
    op.drop_index(op.f("ix_student_progressions_id"), table_name="student_progressions")
    op.drop_index(
        op.f("ix_student_progressions_from_section_id"),
        table_name="student_progressions",
    )
    op.drop_index(
        op.f("ix_student_progressions_from_class_id"), table_name="student_progressions"
    )
    op.drop_index(
        op.f("ix_student_progressions_from_academic_year_id"),
        table_name="student_progressions",
    )
    op.drop_table("student_progressions")
    # ### end Alembic commands ###
