"""create_experiences_table

Revision ID: 5afc091ac86d
Revises: bdbff9bcb092
Create Date: 2026-07-29 13:59:51.457225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5afc091ac86d"
down_revision: str | Sequence[str] | None = "bdbff9bcb092"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "employment_type",
            sa.Enum(
                "FULL_TIME",
                "PART_TIME",
                "CONTRACT",
                "INTERN",
                "FREELANCE",
                name="employmenttype",
            ),
            nullable=False,
        ),
        sa.Column("organization_name", sa.String(length=150), nullable=False),
        sa.Column(
            "organization_type",
            sa.Enum(
                "PRIVATE_SCHOOL",
                "GOVT_SCHOOL",
                "INTERNATIONAL_SCHOOL",
                "PRIVATE_COMPANY",
                "OTHER",
                name="organizationtype",
            ),
            nullable=False,
        ),
        sa.Column("designation", sa.String(length=150), nullable=False),
        sa.Column("department", sa.String(length=150), nullable=True),
        sa.Column("employment_category", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("currently_working", sa.Boolean(), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("experience_months", sa.Integer(), nullable=True),
        sa.Column("salary", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("reason_for_leaving", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column("achievements", sa.Text(), nullable=True),
        sa.Column("skills_used", sa.Text(), nullable=True),
        sa.Column("manager_name", sa.String(length=150), nullable=True),
        sa.Column("manager_email", sa.String(length=150), nullable=True),
        sa.Column("manager_phone", sa.String(length=50), nullable=True),
        sa.Column("reference_available", sa.Boolean(), nullable=False),
        sa.Column("experience_certificate_url", sa.String(length=255), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_by", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="experiencestatus"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verification_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiences_currently_working"),
        "experiences",
        ["currently_working"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experiences_employee_id"), "experiences", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_experiences_id"), "experiences", ["id"], unique=False)
    op.create_index(
        op.f("ix_experiences_is_verified"), "experiences", ["is_verified"], unique=False
    )
    op.create_index(
        op.f("ix_experiences_school_id"), "experiences", ["school_id"], unique=False
    )
    op.create_index(
        op.f("ix_experiences_status"), "experiences", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_experiences_status"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_school_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_is_verified"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_employee_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_currently_working"), table_name="experiences")
    op.drop_table("experiences")
    # ### end Alembic commands ###
