"""create_classes_and_sections_tables

Revision ID: 5c66bc0df22d
Revises: 65b0bdeeb244
Create Date: 2026-07-26 05:05:09.207779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c66bc0df22d"
down_revision: str | Sequence[str] | None = "65b0bdeeb244"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"], ["academic_years.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("academic_year_id", "name", name="uq_classes_ay_name"),
        sa.UniqueConstraint("school_id", "code", name="uq_classes_school_code"),
    )
    op.create_index(
        op.f("ix_classes_academic_year_id"),
        "classes",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(op.f("ix_classes_id"), "classes", ["id"], unique=False)
    op.create_index(
        op.f("ix_classes_school_id"), "classes", ["school_id"], unique=False
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(length=50), nullable=True),
        sa.Column("floor", sa.String(length=50), nullable=True),
        sa.Column("building", sa.String(length=50), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PLANNED", "ACTIVE", "INACTIVE", "ARCHIVED", name="sectionstatus"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"], ["academic_years.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "class_id", "display_order", name="uq_sections_class_display_order"
        ),
        sa.UniqueConstraint("class_id", "name", name="uq_sections_class_name"),
        sa.UniqueConstraint("school_id", "code", name="uq_sections_school_code"),
    )
    op.create_index(
        op.f("ix_sections_academic_year_id"),
        "sections",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sections_class_id"), "sections", ["class_id"], unique=False
    )
    op.create_index(op.f("ix_sections_id"), "sections", ["id"], unique=False)
    op.create_index(
        op.f("ix_sections_school_id"), "sections", ["school_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sections_school_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_class_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_academic_year_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_classes_school_id"), table_name="classes")
    op.drop_index(op.f("ix_classes_id"), table_name="classes")
    op.drop_index(op.f("ix_classes_academic_year_id"), table_name="classes")
    op.drop_table("classes")
    op.execute("DROP TYPE IF EXISTS sectionstatus")
    # ### end Alembic commands ###
