"""create_staff_attendance_tables

Revision ID: 5d4206f8d867
Revises: f0d97f424984
Create Date: 2026-07-29 17:05:08.300979

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4206f8d867"
down_revision: str | Sequence[str] | None = "f0d97f424984"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(length=150), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum(
                "BIOMETRIC",
                "RFID",
                "CAMERA",
                "MOBILE",
                "OTHER",
                name="attendance_device_type",
            ),
            nullable=False,
        ),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "MAINTENANCE",
                "DECOMMISSIONED",
                name="attendance_device_status",
            ),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_devices_device_type"),
        "attendance_devices",
        ["device_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_devices_id"), "attendance_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_devices_school_id"),
        "attendance_devices",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_devices_status"),
        "attendance_devices",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_uq_school_device_serial",
        "attendance_devices",
        ["school_id", "serial_number"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false AND serial_number IS NOT NULL"),
    )
    op.create_table(
        "attendance_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("policy_name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("late_arrival_threshold_minutes", sa.Integer(), nullable=False),
        sa.Column("late_arrival_deduction_minutes", sa.Integer(), nullable=False),
        sa.Column("early_departure_threshold_minutes", sa.Integer(), nullable=False),
        sa.Column("early_departure_deduction_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_threshold_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_enabled", sa.Boolean(), nullable=False),
        sa.Column("weekend_days", sa.String(length=20), nullable=False),
        sa.Column("count_holidays_as_present", sa.Boolean(), nullable=False),
        sa.Column("count_weekends_as_present", sa.Boolean(), nullable=False),
        sa.Column("grace_period_minutes", sa.Integer(), nullable=False),
        sa.Column("auto_half_day_threshold_minutes", sa.Integer(), nullable=True),
        sa.Column("auto_half_day_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_absent_threshold_minutes", sa.Integer(), nullable=True),
        sa.Column("auto_absent_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="attendance_policy_status"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_policies_id"), "attendance_policies", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_policies_school_id"),
        "attendance_policies",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_policies_status"),
        "attendance_policies",
        ["status"],
        unique=False,
    )
    op.create_table(
        "attendance_shifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("shift_code", sa.String(length=50), nullable=False),
        sa.Column("shift_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("break_start", sa.Time(), nullable=True),
        sa.Column("break_end", sa.Time(), nullable=True),
        sa.Column("grace_minutes", sa.Integer(), nullable=False),
        sa.Column("working_hours", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("is_night_shift", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="attendance_shift_status"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_shifts_id"), "attendance_shifts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_shifts_school_id"),
        "attendance_shifts",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_shifts_status"),
        "attendance_shifts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_uq_school_shift_code",
        "attendance_shifts",
        ["school_id", "shift_code"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=True),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("check_in_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("working_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("late_minutes", sa.Integer(), nullable=False),
        sa.Column("early_departure_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PRESENT",
                "ABSENT",
                "HALF_DAY",
                "LATE",
                "EARLY_DEPARTURE",
                "ON_LEAVE",
                "HOLIDAY",
                "WEEKEND",
                "WORK_FROM_HOME",
                name="attendance_record_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "BIOMETRIC",
                "RFID",
                "MOBILE_APP",
                "WEB_PORTAL",
                "API",
                name="attendance_source",
            ),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["shift_id"], ["attendance_shifts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_records_attendance_date"),
        "attendance_records",
        ["attendance_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_employee_id"),
        "attendance_records",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_id"), "attendance_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_records_school_id"),
        "attendance_records",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_shift_id"),
        "attendance_records",
        ["shift_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_source"),
        "attendance_records",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_records_status"),
        "attendance_records",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_uq_employee_attendance_date",
        "attendance_records",
        ["school_id", "employee_id", "attendance_date"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "attendance_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("log_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "BIOMETRIC_DEVICE",
                "API",
                "MANUAL",
                "IMPORT",
                name="attendance_log_source",
            ),
            nullable=False,
        ),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("processed_record_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["device_id"], ["attendance_devices.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["processed_record_id"], ["attendance_records.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_logs_device_id"),
        "attendance_logs",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_logs_employee_id"),
        "attendance_logs",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_logs_id"), "attendance_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_logs_log_timestamp"),
        "attendance_logs",
        ["log_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_logs_school_id"),
        "attendance_logs",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_logs_source"), "attendance_logs", ["source"], unique=False
    )
    op.create_table(
        "attendance_regularizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("attendance_record_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_check_in", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_check_out", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "requested_status",
            sa.Enum(
                "PRESENT",
                "ABSENT",
                "HALF_DAY",
                "LATE",
                "EARLY_DEPARTURE",
                "ON_LEAVE",
                "HOLIDAY",
                "WEEKEND",
                "WORK_FROM_HOME",
                name="regularization_requested_status",
            ),
            nullable=True,
        ),
        sa.Column("approver_id", sa.UUID(), nullable=True),
        sa.Column(
            "approval_status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="regularization_approval_status",
            ),
            nullable=False,
        ),
        sa.Column("approval_remarks", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approver_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["attendance_record_id"], ["attendance_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_regularizations_approval_status"),
        "attendance_regularizations",
        ["approval_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_regularizations_attendance_record_id"),
        "attendance_regularizations",
        ["attendance_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_regularizations_employee_id"),
        "attendance_regularizations",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_regularizations_id"),
        "attendance_regularizations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_regularizations_school_id"),
        "attendance_regularizations",
        ["school_id"],
        unique=False,
    )
    op.drop_table("sort_mock_models")
    op.drop_table("filter_mock_models")
    op.drop_index(
        op.f("ix_pagination_mock_models_id"), table_name="pagination_mock_models"
    )
    op.drop_table("pagination_mock_models")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagination_mock_models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pagination_mock_models_pkey")),
    )
    op.create_index(
        op.f("ix_pagination_mock_models_id"),
        "pagination_mock_models",
        ["id"],
        unique=False,
    )
    op.create_table(
        "filter_mock_models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("filter_mock_models_pkey")),
    )
    op.create_table(
        "sort_mock_models",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rank", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("sort_mock_models_pkey")),
    )
    op.drop_index(
        op.f("ix_attendance_regularizations_school_id"),
        table_name="attendance_regularizations",
    )
    op.drop_index(
        op.f("ix_attendance_regularizations_id"),
        table_name="attendance_regularizations",
    )
    op.drop_index(
        op.f("ix_attendance_regularizations_employee_id"),
        table_name="attendance_regularizations",
    )
    op.drop_index(
        op.f("ix_attendance_regularizations_attendance_record_id"),
        table_name="attendance_regularizations",
    )
    op.drop_index(
        op.f("ix_attendance_regularizations_approval_status"),
        table_name="attendance_regularizations",
    )
    op.drop_table("attendance_regularizations")
    op.drop_index(op.f("ix_attendance_logs_source"), table_name="attendance_logs")
    op.drop_index(op.f("ix_attendance_logs_school_id"), table_name="attendance_logs")
    op.drop_index(
        op.f("ix_attendance_logs_log_timestamp"), table_name="attendance_logs"
    )
    op.drop_index(op.f("ix_attendance_logs_id"), table_name="attendance_logs")
    op.drop_index(op.f("ix_attendance_logs_employee_id"), table_name="attendance_logs")
    op.drop_index(op.f("ix_attendance_logs_device_id"), table_name="attendance_logs")
    op.drop_table("attendance_logs")
    op.drop_index(
        "ix_uq_employee_attendance_date",
        table_name="attendance_records",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_attendance_records_status"), table_name="attendance_records")
    op.drop_index(op.f("ix_attendance_records_source"), table_name="attendance_records")
    op.drop_index(
        op.f("ix_attendance_records_shift_id"), table_name="attendance_records"
    )
    op.drop_index(
        op.f("ix_attendance_records_school_id"), table_name="attendance_records"
    )
    op.drop_index(op.f("ix_attendance_records_id"), table_name="attendance_records")
    op.drop_index(
        op.f("ix_attendance_records_employee_id"), table_name="attendance_records"
    )
    op.drop_index(
        op.f("ix_attendance_records_attendance_date"), table_name="attendance_records"
    )
    op.drop_table("attendance_records")
    op.drop_index(
        "ix_uq_school_shift_code",
        table_name="attendance_shifts",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_attendance_shifts_status"), table_name="attendance_shifts")
    op.drop_index(
        op.f("ix_attendance_shifts_school_id"), table_name="attendance_shifts"
    )
    op.drop_index(op.f("ix_attendance_shifts_id"), table_name="attendance_shifts")
    op.drop_table("attendance_shifts")
    op.drop_index(
        op.f("ix_attendance_policies_status"), table_name="attendance_policies"
    )
    op.drop_index(
        op.f("ix_attendance_policies_school_id"), table_name="attendance_policies"
    )
    op.drop_index(op.f("ix_attendance_policies_id"), table_name="attendance_policies")
    op.drop_table("attendance_policies")
    op.drop_index(
        "ix_uq_school_device_serial",
        table_name="attendance_devices",
        postgresql_where=sa.text("is_deleted = false AND serial_number IS NOT NULL"),
    )
    op.drop_index(op.f("ix_attendance_devices_status"), table_name="attendance_devices")
    op.drop_index(
        op.f("ix_attendance_devices_school_id"), table_name="attendance_devices"
    )
    op.drop_index(op.f("ix_attendance_devices_id"), table_name="attendance_devices")
    op.drop_index(
        op.f("ix_attendance_devices_device_type"), table_name="attendance_devices"
    )
    op.drop_table("attendance_devices")
    # ### end Alembic commands ###
