"""create student document tables

Revision ID: 5fd509cc4d99
Revises: b43b13c7bb1b
Create Date: 2026-07-25 21:05:28.376063

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5fd509cc4d99'
down_revision: str | Sequence[str] | None = 'b43b13c7bb1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PHOTO', 'AADHAAR', 'BIRTH_CERTIFICATE', 'TRANSFER_CERTIFICATE', 'COMMUNITY_CERTIFICATE', 'MEDICAL_CERTIFICATE', 'PASSPORT', 'MARKSHEET', 'ADDRESS_PROOF', 'INCOME_CERTIFICATE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('document_name', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_checksum'), 'student_documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_student_documents_document_type'), 'student_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_index(op.f('ix_student_documents_school_id'), 'student_documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_documents_uploaded_by'), 'student_documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_student_documents_verified_by'), 'student_documents', ['verified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_documents_verified_by'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_uploaded_by'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_school_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_document_type'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_checksum'), table_name='student_documents')
    op.drop_table('student_documents')
    # ### end Alembic commands ###
