"""create_employee_documents_table

Revision ID: 63c3c2e91167
Revises: 5afc091ac86d
Create Date: 2026-07-29 14:10:06.759012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63c3c2e91167"
down_revision: str | Sequence[str] | None = "5afc091ac86d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "IDENTITY_PROOF",
                "ADDRESS_PROOF",
                "ACADEMIC_CERTIFICATE",
                "PROFESSIONAL_DOCUMENT",
                "FINANCIAL_DOCUMENT",
                "COMPLIANCE",
                "OTHER",
                name="employee_document_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "document_category",
            sa.Enum(
                "PERSONAL",
                "ACADEMIC",
                "PROFESSIONAL",
                "FINANCIAL",
                "LEGAL",
                "OTHER",
                name="employee_document_category",
            ),
            nullable=False,
        ),
        sa.Column("document_name", sa.String(length=150), nullable=False),
        sa.Column("document_number", sa.String(length=100), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_provider", sa.String(length=50), nullable=False),
        sa.Column("storage_bucket", sa.String(length=150), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("issued_by", sa.String(length=150), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                name="employee_document_verification_status",
            ),
            nullable=False,
        ),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="employee_document_status"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_documents_document_category"),
        "employee_documents",
        ["document_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_document_type"),
        "employee_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_employee_id"),
        "employee_documents",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_id"), "employee_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_employee_documents_is_expired"),
        "employee_documents",
        ["is_expired"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_school_id"),
        "employee_documents",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_status"),
        "employee_documents",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_documents_verification_status"),
        "employee_documents",
        ["verification_status"],
        unique=False,
    )
    op.create_index(
        "ix_uq_school_emp_doc_num",
        "employee_documents",
        ["school_id", "document_number"],
        unique=True,
        postgresql_where=sa.text("document_number IS NOT NULL AND is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_uq_school_emp_doc_num",
        table_name="employee_documents",
        postgresql_where=sa.text("document_number IS NOT NULL AND is_deleted = false"),
    )
    op.drop_index(
        op.f("ix_employee_documents_verification_status"),
        table_name="employee_documents",
    )
    op.drop_index(op.f("ix_employee_documents_status"), table_name="employee_documents")
    op.drop_index(
        op.f("ix_employee_documents_school_id"), table_name="employee_documents"
    )
    op.drop_index(
        op.f("ix_employee_documents_is_expired"), table_name="employee_documents"
    )
    op.drop_index(op.f("ix_employee_documents_id"), table_name="employee_documents")
    op.drop_index(
        op.f("ix_employee_documents_employee_id"), table_name="employee_documents"
    )
    op.drop_index(
        op.f("ix_employee_documents_document_type"), table_name="employee_documents"
    )
    op.drop_index(
        op.f("ix_employee_documents_document_category"), table_name="employee_documents"
    )
    op.drop_table("employee_documents")
    # ### end Alembic commands ###
