"""create_class_timetable_tables

Revision ID: 68f616e9b0fd
Revises: 4654f14ee87b
Create Date: 2026-08-01 06:46:28.302376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f616e9b0fd'
down_revision: Union[str, Sequence[str], None] = '4654f14ee87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_timetables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='timetable_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_timetables_academic_year_id'), 'class_timetables', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_class_timetables_class_id'), 'class_timetables', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_timetables_id'), 'class_timetables', ['id'], unique=False)
    op.create_index(op.f('ix_class_timetables_school_id'), 'class_timetables', ['school_id'], unique=False)
    op.create_index(op.f('ix_class_timetables_section_id'), 'class_timetables', ['section_id'], unique=False)
    op.create_index(op.f('ix_class_timetables_term_id'), 'class_timetables', ['term_id'], unique=False)
    op.create_index('ix_uq_school_class_timetable_version', 'class_timetables', ['school_id', 'class_id', 'section_id', 'academic_year_id', 'term_id', 'version'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('recurring_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['class_timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_schedules_id'), 'recurring_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_schedules_school_id'), 'recurring_schedules', ['school_id'], unique=False)
    op.create_index(op.f('ix_recurring_schedules_timetable_id'), 'recurring_schedules', ['timetable_id'], unique=False)
    op.create_table('class_timetable_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('teacher_subject_allocation_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.Enum('THEORY', 'PRACTICAL', 'LAB', 'SEMINAR', 'TUTORIAL', name='class_timetable_lesson_type'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_allocation_id'], ['teacher_subject_allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['class_timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_timetable_entries_id'), 'class_timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_room_id'), 'class_timetable_entries', ['room_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_school_id'), 'class_timetable_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_subject_id'), 'class_timetable_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_teacher_id'), 'class_timetable_entries', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_teacher_subject_allocation_id'), 'class_timetable_entries', ['teacher_subject_allocation_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_time_slot_id'), 'class_timetable_entries', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_timetable_id'), 'class_timetable_entries', ['timetable_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_entries_working_day_id'), 'class_timetable_entries', ['working_day_id'], unique=False)
    op.create_index('ix_uq_timetable_entry_slot', 'class_timetable_entries', ['timetable_id', 'working_day_id', 'time_slot_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_timetable_entry_slot', table_name='class_timetable_entries', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_class_timetable_entries_working_day_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_timetable_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_time_slot_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_teacher_subject_allocation_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_teacher_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_subject_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_school_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_room_id'), table_name='class_timetable_entries')
    op.drop_index(op.f('ix_class_timetable_entries_id'), table_name='class_timetable_entries')
    op.drop_table('class_timetable_entries')
    op.drop_index(op.f('ix_recurring_schedules_timetable_id'), table_name='recurring_schedules')
    op.drop_index(op.f('ix_recurring_schedules_school_id'), table_name='recurring_schedules')
    op.drop_index(op.f('ix_recurring_schedules_id'), table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_index('ix_uq_school_class_timetable_version', table_name='class_timetables', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_class_timetables_term_id'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_section_id'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_school_id'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_id'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_class_id'), table_name='class_timetables')
    op.drop_index(op.f('ix_class_timetables_academic_year_id'), table_name='class_timetables')
    op.drop_table('class_timetables')
    # ### end Alembic commands ###
