"""create_curriculums_and_units_tables

Revision ID: 6ac6020e1afb
Revises: de183cb390f3
Create Date: 2026-07-26 09:43:00.244369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ac6020e1afb"
down_revision: str | Sequence[str] | None = "de183cb390f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curriculums",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("class_subject_mapping_id", sa.UUID(), nullable=False),
        sa.Column("curriculum_code", sa.String(length=50), nullable=False),
        sa.Column("curriculum_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("learning_objectives", sa.Text(), nullable=True),
        sa.Column("teaching_methodology", sa.Text(), nullable=True),
        sa.Column("assessment_strategy", sa.Text(), nullable=True),
        sa.Column("reference_books", sa.Text(), nullable=True),
        sa.Column(
            "completion_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("estimated_hours", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "COMPLETED", "ARCHIVED", name="curriculumstatus"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"], ["academic_years.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["class_subject_mapping_id"],
            ["class_subject_mappings.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "curriculum_code", name="uq_curriculums_school_code"
        ),
        sa.UniqueConstraint(
            "school_id", "curriculum_name", name="uq_curriculums_school_name"
        ),
    )
    op.create_index(
        op.f("ix_curriculums_academic_year_id"),
        "curriculums",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_curriculums_class_subject_mapping_id"),
        "curriculums",
        ["class_subject_mapping_id"],
        unique=False,
    )
    op.create_index(op.f("ix_curriculums_id"), "curriculums", ["id"], unique=False)
    op.create_index(
        op.f("ix_curriculums_school_id"), "curriculums", ["school_id"], unique=False
    )
    op.create_index(
        op.f("ix_curriculums_term_id"), "curriculums", ["term_id"], unique=False
    )
    op.create_table(
        "curriculum_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("curriculum_id", sa.UUID(), nullable=False),
        sa.Column("unit_number", sa.Integer(), nullable=False),
        sa.Column("unit_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("learning_outcomes", sa.Text(), nullable=True),
        sa.Column("estimated_hours", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["curriculum_id"], ["curriculums.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "curriculum_id", "display_order", name="uq_curriculum_units_order"
        ),
        sa.UniqueConstraint(
            "curriculum_id", "unit_number", name="uq_curriculum_units_number"
        ),
    )
    op.create_index(
        op.f("ix_curriculum_units_curriculum_id"),
        "curriculum_units",
        ["curriculum_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_curriculum_units_id"), "curriculum_units", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_curriculum_units_school_id"),
        "curriculum_units",
        ["school_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_curriculum_units_school_id"), table_name="curriculum_units")
    op.drop_index(op.f("ix_curriculum_units_id"), table_name="curriculum_units")
    op.drop_index(
        op.f("ix_curriculum_units_curriculum_id"), table_name="curriculum_units"
    )
    op.drop_table("curriculum_units")
    op.drop_index(op.f("ix_curriculums_term_id"), table_name="curriculums")
    op.drop_index(op.f("ix_curriculums_school_id"), table_name="curriculums")
    op.drop_index(op.f("ix_curriculums_id"), table_name="curriculums")
    op.drop_index(
        op.f("ix_curriculums_class_subject_mapping_id"), table_name="curriculums"
    )
    op.drop_index(op.f("ix_curriculums_academic_year_id"), table_name="curriculums")
    op.drop_table("curriculums")
    # ### end Alembic commands ###
