"""create_teacher_timetable_tables

Revision ID: 6e5d797d60e3
Revises: 68f616e9b0fd
Create Date: 2026-08-01 07:00:30.962417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5d797d60e3'
down_revision: Union[str, Sequence[str], None] = '68f616e9b0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='teacher_availability_status'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_availabilities_id'), 'teacher_availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_availabilities_school_id'), 'teacher_availabilities', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_availabilities_teacher_id'), 'teacher_availabilities', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_availabilities_time_slot_id'), 'teacher_availabilities', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_teacher_availabilities_working_day_id'), 'teacher_availabilities', ['working_day_id'], unique=False)
    op.create_index('ix_uq_teacher_availability_slot', 'teacher_availabilities', ['school_id', 'teacher_id', 'working_day_id', 'time_slot_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('teacher_timetables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='teacher_timetable_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_timetables_academic_year_id'), 'teacher_timetables', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_id'), 'teacher_timetables', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_school_id'), 'teacher_timetables', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_teacher_id'), 'teacher_timetables', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetables_term_id'), 'teacher_timetables', ['term_id'], unique=False)
    op.create_index('ix_uq_teacher_timetable_version', 'teacher_timetables', ['school_id', 'teacher_id', 'academic_year_id', 'term_id', 'version'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('teacher_timetable_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_timetable_id', sa.UUID(), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('class_timetable_entry_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('lesson_type', sa.Enum('THEORY', 'PRACTICAL', 'LAB', 'SEMINAR', 'TUTORIAL', name='teacher_timetable_lesson_type'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_timetable_entry_id'], ['class_timetable_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_timetable_id'], ['teacher_timetables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_timetable_entries_class_id'), 'teacher_timetable_entries', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_class_timetable_entry_id'), 'teacher_timetable_entries', ['class_timetable_entry_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_id'), 'teacher_timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_room_id'), 'teacher_timetable_entries', ['room_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_school_id'), 'teacher_timetable_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_section_id'), 'teacher_timetable_entries', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_subject_id'), 'teacher_timetable_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_teacher_timetable_id'), 'teacher_timetable_entries', ['teacher_timetable_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_time_slot_id'), 'teacher_timetable_entries', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_teacher_timetable_entries_working_day_id'), 'teacher_timetable_entries', ['working_day_id'], unique=False)
    op.create_index('ix_uq_teacher_timetable_entry_slot', 'teacher_timetable_entries', ['school_id', 'teacher_timetable_id', 'working_day_id', 'time_slot_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('filter_mock_models')
    op.drop_table('sort_mock_models')
    op.drop_index(op.f('ix_pagination_mock_models_id'), table_name='pagination_mock_models')
    op.drop_table('pagination_mock_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagination_mock_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pagination_mock_models_pkey'))
    )
    op.create_index(op.f('ix_pagination_mock_models_id'), 'pagination_mock_models', ['id'], unique=False)
    op.create_table('sort_mock_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sort_mock_models_pkey'))
    )
    op.create_table('filter_mock_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('filter_mock_models_pkey'))
    )
    op.drop_index('ix_uq_teacher_timetable_entry_slot', table_name='teacher_timetable_entries', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_teacher_timetable_entries_working_day_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_time_slot_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_teacher_timetable_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_subject_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_section_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_school_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_room_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_class_timetable_entry_id'), table_name='teacher_timetable_entries')
    op.drop_index(op.f('ix_teacher_timetable_entries_class_id'), table_name='teacher_timetable_entries')
    op.drop_table('teacher_timetable_entries')
    op.drop_index('ix_uq_teacher_timetable_version', table_name='teacher_timetables', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_teacher_timetables_term_id'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_teacher_timetables_teacher_id'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_teacher_timetables_school_id'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_teacher_timetables_id'), table_name='teacher_timetables')
    op.drop_index(op.f('ix_teacher_timetables_academic_year_id'), table_name='teacher_timetables')
    op.drop_table('teacher_timetables')
    op.drop_index('ix_uq_teacher_availability_slot', table_name='teacher_availabilities', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_teacher_availabilities_working_day_id'), table_name='teacher_availabilities')
    op.drop_index(op.f('ix_teacher_availabilities_time_slot_id'), table_name='teacher_availabilities')
    op.drop_index(op.f('ix_teacher_availabilities_teacher_id'), table_name='teacher_availabilities')
    op.drop_index(op.f('ix_teacher_availabilities_school_id'), table_name='teacher_availabilities')
    op.drop_index(op.f('ix_teacher_availabilities_id'), table_name='teacher_availabilities')
    op.drop_table('teacher_availabilities')
    # ### end Alembic commands ###
