"""create_room_tables

Revision ID: 880d485af3f2
Revises: f85b388b93c4
Create Date: 2026-07-31 19:10:52.725863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880d485af3f2'
down_revision: Union[str, Sequence[str], None] = 'f85b388b93c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('building_code', sa.String(length=50), nullable=False),
    sa.Column('building_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='building_status'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_school_id'), 'buildings', ['school_id'], unique=False)
    op.create_index('ix_uq_school_building_code', 'buildings', ['school_id', 'building_code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_index(op.f('ix_floors_school_id'), 'floors', ['school_id'], unique=False)
    op.create_index('ix_uq_school_building_floor_number', 'floors', ['school_id', 'building_id', 'floor_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=50), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.Enum('CLASSROOM', 'LAB', 'SEMINAR_HALL', 'OFFICE', 'OTHER', name='room_type'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('air_conditioned', sa.Boolean(), nullable=False),
    sa.Column('smart_classroom', sa.Boolean(), nullable=False),
    sa.Column('projector', sa.Boolean(), nullable=False),
    sa.Column('whiteboard', sa.Boolean(), nullable=False),
    sa.Column('computer_lab', sa.Boolean(), nullable=False),
    sa.Column('science_lab', sa.Boolean(), nullable=False),
    sa.Column('internet_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('maintenance_status', sa.Enum('OPERATIONAL', 'UNDER_MAINTENANCE', 'OUT_OF_ORDER', name='room_maintenance_status'), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_building_id'), 'rooms', ['building_id'], unique=False)
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_school_id'), 'rooms', ['school_id'], unique=False)
    op.create_index('ix_uq_school_room_code', 'rooms', ['school_id', 'room_code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('room_allocation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('allowed_class_levels', sa.JSON(), nullable=True),
    sa.Column('allowed_subjects', sa.JSON(), nullable=True),
    sa.Column('preferred_department_id', sa.UUID(), nullable=True),
    sa.Column('maximum_occupancy', sa.Integer(), nullable=False),
    sa.Column('booking_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preferred_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_allocation_rules_id'), 'room_allocation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_room_allocation_rules_room_id'), 'room_allocation_rules', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_allocation_rules_school_id'), 'room_allocation_rules', ['school_id'], unique=False)
    op.create_index('ix_uq_school_room_allocation_rule', 'room_allocation_rules', ['school_id', 'room_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('room_facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('facility_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_facilities_id'), 'room_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_room_facilities_room_id'), 'room_facilities', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_facilities_school_id'), 'room_facilities', ['school_id'], unique=False)
    op.create_index('ix_uq_school_room_facility', 'room_facilities', ['school_id', 'room_id', 'facility_name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_school_room_facility', table_name='room_facilities', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_room_facilities_school_id'), table_name='room_facilities')
    op.drop_index(op.f('ix_room_facilities_room_id'), table_name='room_facilities')
    op.drop_index(op.f('ix_room_facilities_id'), table_name='room_facilities')
    op.drop_table('room_facilities')
    op.drop_index('ix_uq_school_room_allocation_rule', table_name='room_allocation_rules', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_room_allocation_rules_school_id'), table_name='room_allocation_rules')
    op.drop_index(op.f('ix_room_allocation_rules_room_id'), table_name='room_allocation_rules')
    op.drop_index(op.f('ix_room_allocation_rules_id'), table_name='room_allocation_rules')
    op.drop_table('room_allocation_rules')
    op.drop_index('ix_uq_school_room_code', table_name='rooms', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_rooms_school_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_building_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_uq_school_building_floor_number', table_name='floors', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_floors_school_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index('ix_uq_school_building_code', table_name='buildings', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_buildings_school_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
