"""create_subjects_table

Revision ID: 893be610e5bf
Revises: 5c66bc0df22d
Create Date: 2026-07-26 09:09:30.228088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "893be610e5bf"
down_revision: str | Sequence[str] | None = "5c66bc0df22d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("subject_code", sa.String(length=50), nullable=False),
        sa.Column("subject_name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "subject_type",
            sa.Enum(
                "CORE",
                "ELECTIVE",
                "OPTIONAL",
                "LANGUAGE",
                "LAB",
                "ACTIVITY",
                name="subjecttype",
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("credits", sa.Float(), nullable=False),
        sa.Column("weekly_periods", sa.Integer(), nullable=False),
        sa.Column("theory_hours", sa.Integer(), nullable=False),
        sa.Column("practical_hours", sa.Integer(), nullable=False),
        sa.Column("passing_marks", sa.Integer(), nullable=False),
        sa.Column("maximum_marks", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column("is_elective", sa.Boolean(), nullable=False),
        sa.Column("has_practical", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="subjectstatus"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "subject_code", name="uq_subjects_school_code"
        ),
        sa.UniqueConstraint(
            "school_id", "subject_name", name="uq_subjects_school_name"
        ),
    )
    op.create_index(op.f("ix_subjects_id"), "subjects", ["id"], unique=False)
    op.create_index(
        op.f("ix_subjects_school_id"), "subjects", ["school_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subjects_school_id"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_id"), table_name="subjects")
    op.drop_table("subjects")
    op.execute("DROP TYPE IF EXISTS subjecttype")
    op.execute("DROP TYPE IF EXISTS subjectstatus")
    # ### end Alembic commands ###
