"""create_guardian_tables

Revision ID: 965c1afd8714
Revises: 08122a0db6fa
Create Date: 2026-07-25 20:28:42.364208

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "965c1afd8714"
down_revision: str | Sequence[str] | None = "08122a0db6fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardians",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("middle_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "FATHER",
                "MOTHER",
                "GRANDFATHER",
                "GRANDMOTHER",
                "BROTHER",
                "SISTER",
                "UNCLE",
                "AUNT",
                "LEGAL_GUARDIAN",
                "OTHER",
                name="relationship",
            ),
            nullable=False,
        ),
        sa.Column("occupation", sa.String(length=100), nullable=True),
        sa.Column("qualification", sa.String(length=100), nullable=True),
        sa.Column("annual_income", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("alternate_phone", sa.String(length=20), nullable=True),
        sa.Column("aadhaar_number", sa.String(length=12), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("is_primary_guardian", sa.Boolean(), nullable=False),
        sa.Column("is_emergency_contact", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id", "aadhaar_number", name="uq_guardians_school_aadhaar"
        ),
        sa.UniqueConstraint("school_id", "email", name="uq_guardians_school_email"),
        sa.UniqueConstraint("school_id", "phone", name="uq_guardians_school_phone"),
    )
    op.create_index(op.f("ix_guardians_id"), "guardians", ["id"], unique=False)
    op.create_index(
        op.f("ix_guardians_school_id"), "guardians", ["school_id"], unique=False
    )
    op.create_table(
        "student_guardian_mappings",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("guardian_id", sa.UUID(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "FATHER",
                "MOTHER",
                "GRANDFATHER",
                "GRANDMOTHER",
                "BROTHER",
                "SISTER",
                "UNCLE",
                "AUNT",
                "LEGAL_GUARDIAN",
                "OTHER",
                name="relationship",
            ),
            nullable=False,
        ),
        sa.Column("is_primary_guardian", sa.Boolean(), nullable=False),
        sa.Column("is_emergency_contact", sa.Boolean(), nullable=False),
        sa.Column("is_pickup_authorized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["guardian_id"], ["guardians.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("student_id", "guardian_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_guardian_mappings")
    op.drop_index(op.f("ix_guardians_school_id"), table_name="guardians")
    op.drop_index(op.f("ix_guardians_id"), table_name="guardians")
    op.drop_table("guardians")
    # ### end Alembic commands ###
