"""Final verification

Revision ID: 96667da096a1
Revises: e5524792057e
Create Date: 2026-07-25 09:26:27.077329

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "96667da096a1"
down_revision: str | Sequence[str] | None = "e5524792057e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
