"""create_admission_tables

Revision ID: b43b13c7bb1b
Revises: 965c1afd8714
Create Date: 2026-07-25 20:54:14.324607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b43b13c7bb1b"
down_revision: str | Sequence[str] | None = "965c1afd8714"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admission_sequences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("prefix", sa.String(length=50), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admission_sequences_id"), "admission_sequences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_admission_sequences_school_id"),
        "admission_sequences",
        ["school_id"],
        unique=True,
    )
    op.create_table(
        "admissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("application_number", sa.String(length=50), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("academic_year", sa.String(length=20), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("admission_date", sa.Date(), nullable=True),
        sa.Column("application_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WAITLISTED",
                "ENROLLED",
                name="admissionstatus",
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("rejected_by", sa.UUID(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=255), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("documents_verified", sa.Boolean(), nullable=False),
        sa.Column("fees_paid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rejected_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "school_id",
            "application_number",
            name="uq_admissions_school_application_number",
        ),
    )
    op.create_index(
        op.f("ix_admissions_application_number"),
        "admissions",
        ["application_number"],
        unique=False,
    )
    op.create_index(op.f("ix_admissions_id"), "admissions", ["id"], unique=False)
    op.create_index(
        op.f("ix_admissions_school_id"), "admissions", ["school_id"], unique=False
    )
    op.create_index(
        op.f("ix_admissions_student_id"), "admissions", ["student_id"], unique=False
    )
    op.create_table(
        "admission_timelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("admission_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WAITLISTED",
                "ENROLLED",
                name="admissionstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WAITLISTED",
                "ENROLLED",
                name="admissionstatus",
            ),
            nullable=False,
        ),
        sa.Column("action_by", sa.UUID(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["action_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["admission_id"], ["admissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admission_timelines_admission_id"),
        "admission_timelines",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_timelines_id"), "admission_timelines", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admission_timelines_id"), table_name="admission_timelines")
    op.drop_index(
        op.f("ix_admission_timelines_admission_id"), table_name="admission_timelines"
    )
    op.drop_table("admission_timelines")
    op.drop_index(op.f("ix_admissions_student_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_school_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_application_number"), table_name="admissions")
    op.drop_table("admissions")
    op.drop_index(
        op.f("ix_admission_sequences_school_id"), table_name="admission_sequences"
    )
    op.drop_index(op.f("ix_admission_sequences_id"), table_name="admission_sequences")
    op.drop_table("admission_sequences")
    # ### end Alembic commands ###
