"""create_timetable_generator_tables

Revision ID: b5fa717cf510
Revises: 6e5d797d60e3
Create Date: 2026-08-01 07:09:30.880873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fa717cf510'
down_revision: Union[str, Sequence[str], None] = '6e5d797d60e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='timetable_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('total_teachers', sa.Integer(), nullable=False),
    sa.Column('total_subjects', sa.Integer(), nullable=False),
    sa.Column('generated_entries', sa.Integer(), nullable=False),
    sa.Column('failed_entries', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_academic_year_id'), 'generation_jobs', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_school_id'), 'generation_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_term_id'), 'generation_jobs', ['term_id'], unique=False)
    op.create_table('generation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('TEACHER_AVAILABILITY', 'TEACHER_WORKLOAD', 'SUBJECT_LIMIT', 'ROOM_CAPACITY', 'PREFERRED_ROOM', 'PREFERRED_TEACHER', name='timetable_rule_type'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_rules_academic_year_id'), 'generation_rules', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_generation_rules_id'), 'generation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_generation_rules_school_id'), 'generation_rules', ['school_id'], unique=False)
    op.create_index(op.f('ix_generation_rules_term_id'), 'generation_rules', ['term_id'], unique=False)
    op.create_table('generation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_generation_job_id'), 'generation_logs', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_generation_logs_id'), 'generation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_logs_school_id'), 'generation_logs', ['school_id'], unique=False)
    op.create_table('generation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('timetable_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='timetable_result_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['class_timetables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_results_generation_job_id'), 'generation_results', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_generation_results_id'), 'generation_results', ['id'], unique=False)
    op.create_index(op.f('ix_generation_results_school_id'), 'generation_results', ['school_id'], unique=False)
    op.create_index(op.f('ix_generation_results_timetable_id'), 'generation_results', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_results_timetable_id'), table_name='generation_results')
    op.drop_index(op.f('ix_generation_results_school_id'), table_name='generation_results')
    op.drop_index(op.f('ix_generation_results_id'), table_name='generation_results')
    op.drop_index(op.f('ix_generation_results_generation_job_id'), table_name='generation_results')
    op.drop_table('generation_results')
    op.drop_index(op.f('ix_generation_logs_school_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_generation_job_id'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index(op.f('ix_generation_rules_term_id'), table_name='generation_rules')
    op.drop_index(op.f('ix_generation_rules_school_id'), table_name='generation_rules')
    op.drop_index(op.f('ix_generation_rules_id'), table_name='generation_rules')
    op.drop_index(op.f('ix_generation_rules_academic_year_id'), table_name='generation_rules')
    op.drop_table('generation_rules')
    op.drop_index(op.f('ix_generation_jobs_term_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_school_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_academic_year_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
