"""create_qualifications_table

Revision ID: bdbff9bcb092
Revises: 0c1687060520
Create Date: 2026-07-29 13:39:10.269839

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdbff9bcb092"
down_revision: str | Sequence[str] | None = "0c1687060520"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qualifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "qualification_type",
            sa.Enum(
                "SECONDARY",
                "HIGHER_SECONDARY",
                "GRADUATION",
                "POST_GRADUATION",
                "DOCTORATE",
                "DIPLOMA",
                "CERTIFICATION",
                "OTHER",
                name="qualificationtype",
            ),
            nullable=False,
        ),
        sa.Column("qualification_name", sa.String(length=150), nullable=False),
        sa.Column("degree", sa.String(length=150), nullable=True),
        sa.Column("specialization", sa.String(length=150), nullable=True),
        sa.Column("institution_name", sa.String(length=200), nullable=False),
        sa.Column("board_or_university", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column(
            "mode_of_study",
            sa.Enum("FULL_TIME", "PART_TIME", "DISTANCE", "ONLINE", name="modeofstudy"),
            nullable=False,
        ),
        sa.Column("grade", sa.String(length=20), nullable=True),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cgpa", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("cgpa_scale", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("passing_year", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("certificate_number", sa.String(length=100), nullable=True),
        sa.Column("issuing_authority", sa.String(length=150), nullable=True),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("is_highest_qualification", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_by", sa.UUID(), nullable=True),
        sa.Column("document_url", sa.String(length=255), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="qualificationstatus"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verification_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qualifications_employee_id"),
        "qualifications",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qualifications_id"), "qualifications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_qualifications_is_highest_qualification"),
        "qualifications",
        ["is_highest_qualification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qualifications_is_verified"),
        "qualifications",
        ["is_verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qualifications_qualification_type"),
        "qualifications",
        ["qualification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qualifications_school_id"),
        "qualifications",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qualifications_status"), "qualifications", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qualifications_status"), table_name="qualifications")
    op.drop_index(op.f("ix_qualifications_school_id"), table_name="qualifications")
    op.drop_index(
        op.f("ix_qualifications_qualification_type"), table_name="qualifications"
    )
    op.drop_index(op.f("ix_qualifications_is_verified"), table_name="qualifications")
    op.drop_index(
        op.f("ix_qualifications_is_highest_qualification"), table_name="qualifications"
    )
    op.drop_index(op.f("ix_qualifications_id"), table_name="qualifications")
    op.drop_index(op.f("ix_qualifications_employee_id"), table_name="qualifications")
    op.drop_table("qualifications")
    # ### end Alembic commands ###
