"""create_academic_calendar_tables

Revision ID: c582f3021271
Revises: 5d4206f8d867
Create Date: 2026-07-29 20:51:04.222016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c582f3021271'
down_revision: Union[str, Sequence[str], None] = '5d4206f8d867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('holiday_type', sa.Enum('PUBLIC_HOLIDAY', 'REGIONAL_HOLIDAY', 'SCHOOL_HOLIDAY', 'FESTIVAL', 'EMERGENCY_CLOSURE', name='calendar_holiday_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_academic_year_id'), 'holidays', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_index(op.f('ix_holidays_school_id'), 'holidays', ['school_id'], unique=False)
    op.create_table('special_working_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_working_days_academic_year_id'), 'special_working_days', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_special_working_days_id'), 'special_working_days', ['id'], unique=False)
    op.create_index(op.f('ix_special_working_days_school_id'), 'special_working_days', ['school_id'], unique=False)
    op.create_index('ix_uq_school_ay_special_date', 'special_working_days', ['school_id', 'academic_year_id', 'date'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('working_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='calendar_day_of_week'), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('default_break_minutes', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uq_school_ay_day_of_week', 'working_days', ['school_id', 'academic_year_id', 'day_of_week'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_working_days_academic_year_id'), 'working_days', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_working_days_id'), 'working_days', ['id'], unique=False)
    op.create_index(op.f('ix_working_days_school_id'), 'working_days', ['school_id'], unique=False)
    op.create_table('academic_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('event_type', sa.Enum('ACADEMIC', 'EXAM', 'SPORTS', 'HOLIDAY', 'EVENT', 'OTHER', name='calendar_event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('holiday_flag', sa.Boolean(), nullable=False),
    sa.Column('working_day_flag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendar_academic_year_id'), 'academic_calendar', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_calendar_id'), 'academic_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_academic_calendar_school_id'), 'academic_calendar', ['school_id'], unique=False)
    op.create_index(op.f('ix_academic_calendar_term_id'), 'academic_calendar', ['term_id'], unique=False)
    op.create_index('ix_uq_school_ay_calendar_date', 'academic_calendar', ['school_id', 'academic_year_id', 'date'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_school_ay_calendar_date', table_name='academic_calendar', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_academic_calendar_term_id'), table_name='academic_calendar')
    op.drop_index(op.f('ix_academic_calendar_school_id'), table_name='academic_calendar')
    op.drop_index(op.f('ix_academic_calendar_id'), table_name='academic_calendar')
    op.drop_index(op.f('ix_academic_calendar_academic_year_id'), table_name='academic_calendar')
    op.drop_table('academic_calendar')
    op.drop_index(op.f('ix_working_days_school_id'), table_name='working_days')
    op.drop_index(op.f('ix_working_days_id'), table_name='working_days')
    op.drop_index(op.f('ix_working_days_academic_year_id'), table_name='working_days')
    op.drop_index('ix_uq_school_ay_day_of_week', table_name='working_days', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('working_days')
    op.drop_index('ix_uq_school_ay_special_date', table_name='special_working_days', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_special_working_days_school_id'), table_name='special_working_days')
    op.drop_index(op.f('ix_special_working_days_id'), table_name='special_working_days')
    op.drop_index(op.f('ix_special_working_days_academic_year_id'), table_name='special_working_days')
    op.drop_table('special_working_days')
    op.drop_index(op.f('ix_holidays_school_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_academic_year_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
