"""create_designations_table

Revision ID: ce1406c01112
Revises: 49275dbd1101
Create Date: 2026-07-26 18:23:55.868899

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce1406c01112"
down_revision: str | Sequence[str] | None = "49275dbd1101"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("designation_code", sa.String(length=50), nullable=False),
        sa.Column("designation_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("employment_category", sa.String(length=50), nullable=False),
        sa.Column("job_level", sa.String(length=50), nullable=True),
        sa.Column("grade", sa.String(length=50), nullable=True),
        sa.Column("salary_band", sa.String(length=100), nullable=True),
        sa.Column("minimum_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("maximum_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="designationstatus"),
            nullable=False,
        ),
        sa.Column("is_teaching", sa.Boolean(), nullable=False),
        sa.Column("is_management", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "department_id", "designation_name", name="uq_designation_dept_name"
        ),
        sa.UniqueConstraint(
            "school_id", "designation_code", name="uq_designation_school_code"
        ),
    )
    op.create_index(
        op.f("ix_designations_department_id"),
        "designations",
        ["department_id"],
        unique=False,
    )
    op.create_index(op.f("ix_designations_id"), "designations", ["id"], unique=False)
    op.create_index(
        op.f("ix_designations_school_id"), "designations", ["school_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_designations_school_id"), table_name="designations")
    op.drop_index(op.f("ix_designations_id"), table_name="designations")
    op.drop_index(op.f("ix_designations_department_id"), table_name="designations")
    op.drop_table("designations")
    # ### end Alembic commands ###
