"""create student medical tables

Revision ID: d326d7669a9f
Revises: 5fd509cc4d99
Create Date: 2026-07-25 21:14:52.926654

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d326d7669a9f"
down_revision: str | Sequence[str] | None = "5fd509cc4d99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_medical_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum(
                "A_POSITIVE",
                "A_NEGATIVE",
                "B_POSITIVE",
                "B_NEGATIVE",
                "AB_POSITIVE",
                "AB_NEGATIVE",
                "O_POSITIVE",
                "O_NEGATIVE",
                name="bloodgroup",
            ),
            nullable=True,
        ),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("bmi", sa.Float(), nullable=True),
        sa.Column("vision_left", sa.String(length=10), nullable=True),
        sa.Column("vision_right", sa.String(length=10), nullable=True),
        sa.Column("hearing_status", sa.String(length=50), nullable=True),
        sa.Column("medical_conditions", sa.Text(), nullable=True),
        sa.Column("chronic_diseases", sa.Text(), nullable=True),
        sa.Column("current_medications", sa.Text(), nullable=True),
        sa.Column("doctor_name", sa.String(length=100), nullable=True),
        sa.Column("hospital_name", sa.String(length=100), nullable=True),
        sa.Column("doctor_phone", sa.String(length=20), nullable=True),
        sa.Column("insurance_provider", sa.String(length=100), nullable=True),
        sa.Column("insurance_policy_number", sa.String(length=100), nullable=True),
        sa.Column("medical_notes", sa.Text(), nullable=True),
        sa.Column("is_fit_for_school", sa.Boolean(), nullable=False),
        sa.Column("last_medical_checkup", sa.Date(), nullable=True),
        sa.Column("next_medical_checkup", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_medical_records_id"),
        "student_medical_records",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_medical_records_school_id"),
        "student_medical_records",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_medical_records_student_id"),
        "student_medical_records",
        ["student_id"],
        unique=True,
    )
    op.create_table(
        "allergies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medical_record_id", sa.UUID(), nullable=False),
        sa.Column("allergy_name", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "SEVERE", name="allergyseverity"),
            nullable=False,
        ),
        sa.Column("reaction", sa.String(length=200), nullable=True),
        sa.Column("treatment", sa.String(length=200), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["medical_record_id"], ["student_medical_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_allergies_id"), "allergies", ["id"], unique=False)
    op.create_index(
        op.f("ix_allergies_medical_record_id"),
        "allergies",
        ["medical_record_id"],
        unique=False,
    )
    op.create_table(
        "vaccinations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medical_record_id", sa.UUID(), nullable=False),
        sa.Column("vaccine_name", sa.String(length=100), nullable=False),
        sa.Column("dose_number", sa.Integer(), nullable=False),
        sa.Column("vaccination_date", sa.Date(), nullable=False),
        sa.Column("next_due_date", sa.Date(), nullable=True),
        sa.Column("hospital", sa.String(length=100), nullable=True),
        sa.Column("doctor", sa.String(length=100), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["medical_record_id"], ["student_medical_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vaccinations_id"), "vaccinations", ["id"], unique=False)
    op.create_index(
        op.f("ix_vaccinations_medical_record_id"),
        "vaccinations",
        ["medical_record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vaccinations_medical_record_id"), table_name="vaccinations")
    op.drop_index(op.f("ix_vaccinations_id"), table_name="vaccinations")
    op.drop_table("vaccinations")
    op.drop_index(op.f("ix_allergies_medical_record_id"), table_name="allergies")
    op.drop_index(op.f("ix_allergies_id"), table_name="allergies")
    op.drop_table("allergies")
    op.drop_index(
        op.f("ix_student_medical_records_student_id"),
        table_name="student_medical_records",
    )
    op.drop_index(
        op.f("ix_student_medical_records_school_id"),
        table_name="student_medical_records",
    )
    op.drop_index(
        op.f("ix_student_medical_records_id"), table_name="student_medical_records"
    )
    op.drop_table("student_medical_records")
    # ### end Alembic commands ###
