"""create_class_subject_mappings_table

Revision ID: de183cb390f3
Revises: 248db750e199
Create Date: 2026-07-26 09:34:46.869327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de183cb390f3"
down_revision: str | Sequence[str] | None = "248db750e199"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_subject_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("subject_group_id", sa.UUID(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("weekly_periods", sa.Integer(), nullable=False),
        sa.Column("theory_periods", sa.Integer(), nullable=False),
        sa.Column("practical_periods", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("is_compulsory", sa.Boolean(), nullable=False),
        sa.Column("is_elective", sa.Boolean(), nullable=False),
        sa.Column("include_in_result", sa.Boolean(), nullable=False),
        sa.Column("include_in_attendance", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="classsubjectstatus"),
            nullable=False,
        ),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"], ["academic_years.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subject_group_id"], ["subject_groups.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["term_id"], ["terms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "academic_year_id",
            "term_id",
            "class_id",
            "section_id",
            "subject_id",
            name="uq_class_subject_mapping_unique",
        ),
        sa.UniqueConstraint(
            "class_id",
            "term_id",
            "display_order",
            name="uq_class_subject_display_order",
        ),
    )
    op.create_index(
        op.f("ix_class_subject_mappings_academic_year_id"),
        "class_subject_mappings",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_class_id"),
        "class_subject_mappings",
        ["class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_id"),
        "class_subject_mappings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_school_id"),
        "class_subject_mappings",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_section_id"),
        "class_subject_mappings",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_subject_group_id"),
        "class_subject_mappings",
        ["subject_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_subject_id"),
        "class_subject_mappings",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_class_subject_mappings_term_id"),
        "class_subject_mappings",
        ["term_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_class_subject_mappings_term_id"), table_name="class_subject_mappings"
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_subject_id"),
        table_name="class_subject_mappings",
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_subject_group_id"),
        table_name="class_subject_mappings",
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_section_id"),
        table_name="class_subject_mappings",
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_school_id"), table_name="class_subject_mappings"
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_id"), table_name="class_subject_mappings"
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_class_id"), table_name="class_subject_mappings"
    )
    op.drop_index(
        op.f("ix_class_subject_mappings_academic_year_id"),
        table_name="class_subject_mappings",
    )
    op.drop_table("class_subject_mappings")
    op.execute("DROP TYPE IF EXISTS classsubjectstatus")
    # ### end Alembic commands ###
