"""Final database verification

Revision ID: e5524792057e
Revises: 84802920e7db
Create Date: 2026-07-25 09:09:54.910715

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e5524792057e"
down_revision: str | Sequence[str] | None = "84802920e7db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
