"""create_timetable_conflict_tables

Revision ID: ec7518460191
Revises: b5fa717cf510
Create Date: 2026-08-01 07:21:22.375536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7518460191'
down_revision: Union[str, Sequence[str], None] = 'b5fa717cf510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflict_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('conflict_type', sa.Enum('TEACHER_DOUBLE_BOOKING', 'ROOM_DOUBLE_BOOKING', 'CLASS_DOUBLE_BOOKING', 'TEACHER_LEAVE_CONFLICT', 'HOLIDAY_CONFLICT', 'MAX_WORKLOAD', 'ROOM_CAPACITY', 'TEACHER_AVAILABILITY', name='timetable_conflict_type'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', name='timetable_conflict_severity'), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'IGNORED', name='timetable_conflict_status'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_records_class_id'), 'conflict_records', ['class_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_generation_job_id'), 'conflict_records', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_id'), 'conflict_records', ['id'], unique=False)
    op.create_index(op.f('ix_conflict_records_room_id'), 'conflict_records', ['room_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_school_id'), 'conflict_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_section_id'), 'conflict_records', ['section_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_subject_id'), 'conflict_records', ['subject_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_teacher_id'), 'conflict_records', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_time_slot_id'), 'conflict_records', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_conflict_records_working_day_id'), 'conflict_records', ['working_day_id'], unique=False)
    op.create_table('conflict_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('conflict_record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conflict_record_id'], ['conflict_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_logs_conflict_record_id'), 'conflict_logs', ['conflict_record_id'], unique=False)
    op.create_index(op.f('ix_conflict_logs_id'), 'conflict_logs', ['id'], unique=False)
    op.create_index(op.f('ix_conflict_logs_school_id'), 'conflict_logs', ['school_id'], unique=False)
    op.create_table('conflict_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('conflict_record_id', sa.UUID(), nullable=False),
    sa.Column('resolution_strategy', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conflict_record_id'], ['conflict_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_resolutions_conflict_record_id'), 'conflict_resolutions', ['conflict_record_id'], unique=False)
    op.create_index(op.f('ix_conflict_resolutions_id'), 'conflict_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_conflict_resolutions_school_id'), 'conflict_resolutions', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflict_resolutions_school_id'), table_name='conflict_resolutions')
    op.drop_index(op.f('ix_conflict_resolutions_id'), table_name='conflict_resolutions')
    op.drop_index(op.f('ix_conflict_resolutions_conflict_record_id'), table_name='conflict_resolutions')
    op.drop_table('conflict_resolutions')
    op.drop_index(op.f('ix_conflict_logs_school_id'), table_name='conflict_logs')
    op.drop_index(op.f('ix_conflict_logs_id'), table_name='conflict_logs')
    op.drop_index(op.f('ix_conflict_logs_conflict_record_id'), table_name='conflict_logs')
    op.drop_table('conflict_logs')
    op.drop_index(op.f('ix_conflict_records_working_day_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_time_slot_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_teacher_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_subject_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_section_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_school_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_room_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_generation_job_id'), table_name='conflict_records')
    op.drop_index(op.f('ix_conflict_records_class_id'), table_name='conflict_records')
    op.drop_table('conflict_records')
    # ### end Alembic commands ###
