"""create_leave_management_tables

Revision ID: f0d97f424984
Revises: 63c3c2e91167
Create Date: 2026-07-29 14:35:23.429141

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0d97f424984"
down_revision: str | Sequence[str] | None = "63c3c2e91167"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holiday_calendar",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("holiday_name", sa.String(length=150), nullable=False),
        sa.Column(
            "holiday_type",
            sa.Enum(
                "PUBLIC", "ACADEMIC", "REGIONAL", "OTHER", name="leave_holiday_type"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_holiday_calendar_holiday_type"),
        "holiday_calendar",
        ["holiday_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_holiday_calendar_id"), "holiday_calendar", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_holiday_calendar_school_id"),
        "holiday_calendar",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        "ix_uq_school_holiday_date",
        "holiday_calendar",
        ["school_id", "holiday_date"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "leave_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("leave_code", sa.String(length=50), nullable=False),
        sa.Column("leave_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("annual_quota", sa.Integer(), nullable=False),
        sa.Column("carry_forward", sa.Boolean(), nullable=False),
        sa.Column("maximum_carry_forward", sa.Integer(), nullable=False),
        sa.Column("encashment_allowed", sa.Boolean(), nullable=False),
        sa.Column("requires_attachment", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("paid_leave", sa.Boolean(), nullable=False),
        sa.Column(
            "gender_restriction",
            sa.Enum("ALL", "MALE", "FEMALE", "OTHER", name="leave_gender_restriction"),
            nullable=False,
        ),
        sa.Column("minimum_service_days", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "ARCHIVED", name="leave_status"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leave_types_id"), "leave_types", ["id"], unique=False)
    op.create_index(
        op.f("ix_leave_types_school_id"), "leave_types", ["school_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_types_status"), "leave_types", ["status"], unique=False
    )
    op.create_index(
        "ix_uq_school_leave_code",
        "leave_types",
        ["school_id", "leave_code"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "leave_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("designation_id", sa.UUID(), nullable=True),
        sa.Column("employee_type", sa.String(length=50), nullable=True),
        sa.Column("probation_rules", sa.Text(), nullable=True),
        sa.Column("carry_forward_rules", sa.Text(), nullable=True),
        sa.Column("monthly_accrual", sa.Boolean(), nullable=False),
        sa.Column("accrual_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("allow_half_day", sa.Boolean(), nullable=False),
        sa.Column("max_consecutive_days", sa.Integer(), nullable=True),
        sa.Column("minimum_notice_days", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="leave_policy_status"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["designation_id"], ["designations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_id"], ["leave_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_policies_department_id"),
        "leave_policies",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_policies_designation_id"),
        "leave_policies",
        ["designation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_policies_employee_type"),
        "leave_policies",
        ["employee_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_policies_id"), "leave_policies", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_policies_leave_type_id"),
        "leave_policies",
        ["leave_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_policies_school_id"),
        "leave_policies",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_policies_status"), "leave_policies", ["status"], unique=False
    )
    op.create_table(
        "leave_balances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("earned", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("used", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("carry_forward", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "remaining_balance", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["leave_type_id"], ["leave_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_balances_employee_id"),
        "leave_balances",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balances_id"), "leave_balances", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_balances_leave_type_id"),
        "leave_balances",
        ["leave_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balances_school_id"),
        "leave_balances",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balances_year"), "leave_balances", ["year"], unique=False
    )
    op.create_index(
        "ix_uq_school_leave_balance",
        "leave_balances",
        ["school_id", "employee_id", "leave_type_id", "year"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_days", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("half_day", sa.Boolean(), nullable=False),
        sa.Column(
            "half_day_session",
            sa.Enum("FIRST_HALF", "SECOND_HALF", name="leave_half_day_session"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="leave_request_status",
            ),
            nullable=False,
        ),
        sa.Column("submitted_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["leave_type_id"], ["leave_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_requests_employee_id"),
        "leave_requests",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_id"), "leave_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_leave_type_id"),
        "leave_requests",
        ["leave_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_school_id"),
        "leave_requests",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_status"), "leave_requests", ["status"], unique=False
    )
    op.create_table(
        "leave_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("approver_id", sa.UUID(), nullable=False),
        sa.Column("approval_level", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="leave_approval_status"),
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("approval_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["approver_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["leave_request_id"], ["leave_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_approvals_approver_id"),
        "leave_approvals",
        ["approver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_approvals_id"), "leave_approvals", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_approvals_leave_request_id"),
        "leave_approvals",
        ["leave_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_approvals_school_id"),
        "leave_approvals",
        ["school_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_approvals_status"), "leave_approvals", ["status"], unique=False
    )
    op.create_table(
        "leave_attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_request_id"], ["leave_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_attachments_id"), "leave_attachments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_attachments_leave_request_id"),
        "leave_attachments",
        ["leave_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_attachments_school_id"),
        "leave_attachments",
        ["school_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_leave_attachments_school_id"), table_name="leave_attachments"
    )
    op.drop_index(
        op.f("ix_leave_attachments_leave_request_id"), table_name="leave_attachments"
    )
    op.drop_index(op.f("ix_leave_attachments_id"), table_name="leave_attachments")
    op.drop_table("leave_attachments")
    op.drop_index(op.f("ix_leave_approvals_status"), table_name="leave_approvals")
    op.drop_index(op.f("ix_leave_approvals_school_id"), table_name="leave_approvals")
    op.drop_index(
        op.f("ix_leave_approvals_leave_request_id"), table_name="leave_approvals"
    )
    op.drop_index(op.f("ix_leave_approvals_id"), table_name="leave_approvals")
    op.drop_index(op.f("ix_leave_approvals_approver_id"), table_name="leave_approvals")
    op.drop_table("leave_approvals")
    op.drop_index(op.f("ix_leave_requests_status"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_school_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_leave_type_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_employee_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(
        "ix_uq_school_leave_balance",
        table_name="leave_balances",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_leave_balances_year"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_school_id"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_leave_type_id"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_id"), table_name="leave_balances")
    op.drop_index(op.f("ix_leave_balances_employee_id"), table_name="leave_balances")
    op.drop_table("leave_balances")
    op.drop_index(op.f("ix_leave_policies_status"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_school_id"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_leave_type_id"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_id"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_employee_type"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_designation_id"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_department_id"), table_name="leave_policies")
    op.drop_table("leave_policies")
    op.drop_index(
        "ix_uq_school_leave_code",
        table_name="leave_types",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_leave_types_status"), table_name="leave_types")
    op.drop_index(op.f("ix_leave_types_school_id"), table_name="leave_types")
    op.drop_index(op.f("ix_leave_types_id"), table_name="leave_types")
    op.drop_table("leave_types")
    op.drop_index(
        "ix_uq_school_holiday_date",
        table_name="holiday_calendar",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_holiday_calendar_school_id"), table_name="holiday_calendar")
    op.drop_index(op.f("ix_holiday_calendar_id"), table_name="holiday_calendar")
    op.drop_index(
        op.f("ix_holiday_calendar_holiday_type"), table_name="holiday_calendar"
    )
    op.drop_table("holiday_calendar")
    # ### end Alembic commands ###
