"""create_employees_table

Revision ID: f49bf9343b8e
Revises: ce1406c01112
Create Date: 2026-07-26 18:35:41.362101

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f49bf9343b8e"
down_revision: str | Sequence[str] | None = "ce1406c01112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("designation_id", sa.UUID(), nullable=False),
        sa.Column("employee_number", sa.String(length=50), nullable=False),
        sa.Column(
            "employee_type",
            sa.Enum(
                "TEACHING", "NON_TEACHING", "ADMIN", "SUPPORT", name="employeetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "employment_status",
            sa.Enum(
                "PROBATION",
                "CONFIRMED",
                "CONTRACT",
                "RESIGNED",
                "TERMINATED",
                name="employmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("joining_date", sa.Date(), nullable=False),
        sa.Column("confirmation_date", sa.Date(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum(
                "A_PLUS",
                "A_MINUS",
                "B_PLUS",
                "B_MINUS",
                "AB_PLUS",
                "AB_MINUS",
                "O_PLUS",
                "O_MINUS",
                name="employee_blood_group",
            ),
            nullable=True,
        ),
        sa.Column(
            "marital_status",
            sa.Enum("SINGLE", "MARRIED", "DIVORCED", "WIDOWED", name="maritalstatus"),
            nullable=True,
        ),
        sa.Column("nationality", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("alternate_phone", sa.String(length=20), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=20), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("profile_photo_url", sa.String(length=255), nullable=True),
        sa.Column("aadhaar_number", sa.Text(), nullable=True),
        sa.Column("pan_number", sa.Text(), nullable=True),
        sa.Column("passport_number", sa.Text(), nullable=True),
        sa.Column("bank_name", sa.String(length=100), nullable=True),
        sa.Column("bank_account_number", sa.Text(), nullable=True),
        sa.Column("ifsc_code", sa.String(length=20), nullable=True),
        sa.Column(
            "salary_type",
            sa.Enum("MONTHLY", "WEEKLY", "HOURLY", name="salarytype"),
            nullable=False,
        ),
        sa.Column("basic_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["designation_id"], ["designations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "email", name="uq_employees_school_email"),
        sa.UniqueConstraint(
            "school_id", "employee_number", name="uq_employees_school_number"
        ),
        sa.UniqueConstraint("school_id", "phone", name="uq_employees_school_phone"),
    )
    op.create_index(
        op.f("ix_employees_department_id"), "employees", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_employees_designation_id"),
        "employees",
        ["designation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_index(
        op.f("ix_employees_school_id"), "employees", ["school_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_school_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_designation_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_department_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
