"""create_time_slot_tables

Revision ID: f85b388b93c4
Revises: c582f3021271
Create Date: 2026-07-29 21:06:36.318346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85b388b93c4'
down_revision: Union[str, Sequence[str], None] = 'c582f3021271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.Enum('TEACHING', 'BREAK', 'OTHER', name='timeslot_slot_type'), nullable=False),
    sa.Column('working_day_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('is_teaching', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['working_day_id'], ['working_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_academic_year_id'), 'time_slots', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    op.create_index(op.f('ix_time_slots_school_id'), 'time_slots', ['school_id'], unique=False)
    op.create_index(op.f('ix_time_slots_working_day_id'), 'time_slots', ['working_day_id'], unique=False)
    op.create_index('ix_uq_school_wd_display_order', 'time_slots', ['school_id', 'working_day_id', 'display_order'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_uq_school_wd_slot_number', 'time_slots', ['school_id', 'working_day_id', 'slot_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('break_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('break_type', sa.Enum('SHORT_BREAK', 'LUNCH_BREAK', 'PRAYER_BREAK', 'OTHER', name='break_period_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_periods_id'), 'break_periods', ['id'], unique=False)
    op.create_index(op.f('ix_break_periods_school_id'), 'break_periods', ['school_id'], unique=False)
    op.create_index(op.f('ix_break_periods_time_slot_id'), 'break_periods', ['time_slot_id'], unique=False)
    op.create_index('ix_uq_school_ts_break', 'break_periods', ['school_id', 'time_slot_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('default_subject_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_teacher_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_class_id'), 'periods', ['class_id'], unique=False)
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.create_index(op.f('ix_periods_school_id'), 'periods', ['school_id'], unique=False)
    op.create_index(op.f('ix_periods_time_slot_id'), 'periods', ['time_slot_id'], unique=False)
    op.create_index('ix_uq_school_ts_class', 'periods', ['school_id', 'time_slot_id', 'class_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_school_ts_class', table_name='periods', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_periods_time_slot_id'), table_name='periods')
    op.drop_index(op.f('ix_periods_school_id'), table_name='periods')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_index(op.f('ix_periods_class_id'), table_name='periods')
    op.drop_table('periods')
    op.drop_index('ix_uq_school_ts_break', table_name='break_periods', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_break_periods_time_slot_id'), table_name='break_periods')
    op.drop_index(op.f('ix_break_periods_school_id'), table_name='break_periods')
    op.drop_index(op.f('ix_break_periods_id'), table_name='break_periods')
    op.drop_table('break_periods')
    op.drop_index('ix_uq_school_wd_slot_number', table_name='time_slots', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_uq_school_wd_display_order', table_name='time_slots', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_time_slots_working_day_id'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_school_id'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_academic_year_id'), table_name='time_slots')
    op.drop_table('time_slots')
    # ### end Alembic commands ###
